### ISSUE TITLE
Record write attempts in status for current generation

### ISSUE THREAD

**Issue by philbrookes** [Kuadrant/dns-operator#34]
**What**

Whenever a write to the Cloud Provider occurs, we need to emit a metric noting the occurrence which includes the generation.

Add a condition on the status whenever we write to Cloud Provider, e.g.:
```
writeCount: <N>
firstWrite: <timestamp>
Reason: <human message>
```

Reset the count if either:
- Generation of DNS Record is different to observedGeneration
- Plan is empty

We will need to set an upper limit to how many sequential writes are permitted before the controller stops trying so frequently and exposes an error in the status.

When a status with writeCount zero is present, the DNS Record should also have a accepted status of true.

**Comment by philbrookes** [comment]
@david-martin do you have any thoughts on the metric we are considering emitting here? Is this already going to be covered by kube state metrics as we are writing the details to the status.

**Comment by david-martin** [comment]
> Is this already going to be covered by kube state metrics as we are writing the details to the status.

The state metrics config for DNSPolicy is https://github.com/Kuadrant/gateway-api-state-metrics/blob/f37b923fb6789d875992b71a1a88be3899995728/config/default/custom-resource-state.yaml#L514-L566

It can be extended to have different state information, however it might be better to have the metrics you think are valuable be emitted from the controller itself rather than depend on a separate library.
That would allow for easier consumption, alerting and visualisation of metrics.

The write count sounds like a good candidate for a counter metric, with some label for the DNS record name and namespace.
The firstWrite sounds like a good candidate for a gauge that's set to the timestamp, again having the DNS record name and namespace labels.

I would avoid having the reason message be in any metric name or label as it sounds like it could vary a lot.
